// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(WebApiContext))]
    partial class WebApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.7.22376.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webapi.Models.Categoria", b =>
                {
                    b.Property<Guid>("categoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("peso")
                        .HasColumnType("int");

                    b.HasKey("categoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            categoriaId = new Guid("f9f478c4-e823-4766-ac30-6570108c2f61"),
                            nombre = "Actividades pendientes",
                            peso = 20
                        },
                        new
                        {
                            categoriaId = new Guid("e1537fd4-6677-484b-b4f9-dcaf735a2e30"),
                            descripcion = "Cocinar",
                            nombre = "Actividades personales",
                            peso = 50
                        });
                });

            modelBuilder.Entity("webapi.Models.Tarea", b =>
                {
                    b.Property<Guid>("tareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("categoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaFinal")
                        .HasColumnType("datetime2");

                    b.Property<string>("prioridadTarea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("tareaId");

                    b.HasIndex("categoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            tareaId = new Guid("e66a8239-b479-4028-857a-b6949571c0fa"),
                            categoriaId = new Guid("f9f478c4-e823-4766-ac30-6570108c2f61"),
                            descripcion = "Curso de API's",
                            fechaCreacion = new DateTime(2022, 8, 21, 23, 1, 49, 608, DateTimeKind.Local).AddTicks(1955),
                            fechaFinal = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            prioridadTarea = "Alta",
                            titulo = "Ver cursos de .NET"
                        },
                        new
                        {
                            tareaId = new Guid("17d71731-4dbc-4cad-9488-d03cb5e9f9e1"),
                            categoriaId = new Guid("f9f478c4-e823-4766-ac30-6570108c2f61"),
                            descripcion = "Curso de angular",
                            fechaCreacion = new DateTime(2022, 8, 21, 23, 1, 49, 608, DateTimeKind.Local).AddTicks(1968),
                            fechaFinal = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            prioridadTarea = "Alta",
                            titulo = "Ver cursos de Angular"
                        },
                        new
                        {
                            tareaId = new Guid("1fd0ad0c-f877-43a0-ae29-c88db61ba0e4"),
                            categoriaId = new Guid("e1537fd4-6677-484b-b4f9-dcaf735a2e30"),
                            descripcion = "Papas fritas, lechuga y crema de mani",
                            fechaCreacion = new DateTime(2022, 8, 21, 23, 1, 49, 608, DateTimeKind.Local).AddTicks(1970),
                            fechaFinal = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            prioridadTarea = "Media",
                            titulo = "Hacer compras semanales"
                        });
                });

            modelBuilder.Entity("webapi.Models.Tarea", b =>
                {
                    b.HasOne("webapi.Models.Categoria", "categoria")
                        .WithMany("tareas")
                        .HasForeignKey("categoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoria");
                });

            modelBuilder.Entity("webapi.Models.Categoria", b =>
                {
                    b.Navigation("tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
